### ISSUE TITLE
Resueltos: Archivos no legibles

### ISSUE THREAD

**Issue by herrera-ignacio** [Gahen/practicas-resueltas-fcen-algebra1#1]
Hola Gahen!! Por alguna razón cuando trato de abrir los archivos de las prácticas resueltos con LyX, se me genera el error de que no son legibles. Actualmente también estoy utilizando los que subiste de Análisis sin problemas, por eso quería saber si de casualidad hay algún error en los archivos o es problema de mi LyX, estoy utilizando la versión 2.3.

**Comment by Gahen** [comment]
Hola! Acabo de probar abrir los 3 archivos .lyx de la carpeta "resueltos" y me abrieron bien 🤔 Igual el primero me tiró una advertencia sobre una referencia faltante (algo sobre `article`) pero ninguno tuvo problemas en abrir. Te recomiendo probar resetear cualqueir configuración de lyx que tengas.

Probé con la versión 2.2.3 que es la ultima que tiene brew (desgraciadamente estoy en Mac, pero los cree en Linux)

**Comment by herrera-ignacio** [comment]
Justo te respondí al mail Gahen antes de entrar a leer esto perdón! mmm lo tengo como lo bajé y nunca lo había instalado así que debería estar todo por defecto. Estoy en Windows y no creo que el s.o tenga que ver pero por si las dudas mañana probaré instalarlo en Linux a ver si hay alguna diferencia, claramente el problema está en mi LyX, gracias por todo tu tiempo Gahen!!!

**Comment by herrera-ignacio** [comment]
Gahen hola, problema solucionado. Aparentemente el error me lo generaba que estaba bajando cada archivo individualmente, por alguna razón cuando cloné el repositorio entero y lo abrí así, se abre sin problemas. Disculpa las molestias y muchas gracias por tu tiempo!
